services:
  - type: web
    name: frases-backend
    rootDir: FrasesMotivacionales
    # Le dice a Render que use el Dockerfile en la ruta especificada.
    dockerfilePath: FrasesMotivacionales/Dockerfile
    envVars:
      
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false